import React from 'react'
import styles from "../styles/landpgcard.module.css";
function Landpgcard() {
    return (
        <>
               <div className='container'>
                <div className='row'>
                    <h1 className={styles.h1}>Testimonials</h1>
                    <div className={styles.d1} >WHAT CLIENTS SAY
                    <div className={styles.d2} ></div></div>
                    
                </div>
               </div>
            <div className='container'>
                <div className={styles.flexbox}>
                    <div className={styles.col1}>
                      
                            <div className={styles.p1}>Fracht Group</div>
                            <div className={styles.star}>
                            <span className="fa fa-star checked"style={{fontSize:'30px',color:'#f0c546',}}></span>
                             <span className="fa fa-star checked"style={{fontSize:'30px',color:'#f0c546'}}></span>
                            <span className="fa fa-star checked"style={{fontSize:'30px',color:'#f0c546'}}></span>
                            <span className="fa fa-star"style={{fontSize:'30px',color:'#f0c546'}}></span>
                            <span className="fa fa-star"style={{fontSize:'30px',color:'#f0c546'}}></span>

                            </div>
                            
                            <p className={styles.p2}>Their expertise in project accounting allowed us to optimize our project costs and improve efficiency</p>

                         
                       
                    </div>

                    <div className={styles.col1}>
                  
                        <div className={styles.p1}>Bioelys</div>
                            <div className={styles.star}>
                            <span className="fa fa-star checked"style={{fontSize:'30px',color:'#f0c546',}}></span>
                             <span className="fa fa-star checked"style={{fontSize:'30px',color:'#f0c546'}}></span>
                            <span className="fa fa-star checked"style={{fontSize:'30px',color:'#f0c546'}}></span>
                            <span className="fa fa-star"style={{fontSize:'30px',color:'#f0c546'}}></span>
                            <span className="fa fa-star"style={{fontSize:'30px',color:'#f0c546'}}></span>

                            </div>
                            
                            <p className={styles.p2}>The financial reports generated by Maxims Auditors and consultants provided valuable insights into our business and helped us make informed decisions.</p>
                        
                    </div>
                    <div className={styles.col1}>
             
                        <div className={styles.p1}>ALJAR Trading</div>
                            <div className={styles.star}>
                            <span className="fa fa-star checked"style={{fontSize:'30px',color:'#f0c546',}}></span>
                             <span className="fa fa-star checked"style={{fontSize:'30px',color:'#f0c546'}}></span>
                            <span className="fa fa-star checked"style={{fontSize:'30px',color:'#f0c546'}}></span>
                            <span className="fa fa-star"style={{fontSize:'30px',color:'#f0c546'}}></span>
                            <span className="fa fa-star"style={{fontSize:'30px',color:'#f0c546'}}></span>

                            </div>
                            
                            <p className={styles.p2}>Their ability to manage large amounts of data ensured that all of our project records were complete and accurate.</p>
                        
                    </div>
                    <div className={styles.col1}>
                        
                        <div className={styles.p1}>INTRADE commodites</div>
                            <div className={styles.star}>
                            <span className="fa fa-star checked"style={{fontSize:'30px',color:'#f0c546',}}></span>
                             <span className="fa fa-star checked"style={{fontSize:'30px',color:'#f0c546'}}></span>
                            <span className="fa fa-star checked"style={{fontSize:'30px',color:'#f0c546'}}></span>
                            <span className="fa fa-star"style={{fontSize:'30px',color:'#f0c546'}}></span>
                            <span className="fa fa-star"style={{fontSize:'30px',color:'#f0c546'}}></span>

                            </div>
                            
                            <p className={styles.p2}>Their comprehensive stock analysis allowed us to identify areas for improvement in our inter-company management.</p>
                        
                    </div>
                </div>
            </div>


        </>
    );
}

export default Landpgcard;