import React from "react";
import styles from "../styles/testimonialcards.module.css";
import Slider from "react-slick";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

function Testimonialcards() {
  const settings = {
    dots: false,
    infinite: true,
    speed: 500,
    slidesToShow: 4,
    slidesToScroll: 1,
    autoplay: true,
    responsive: [
        {
            breakpoint: 2560,
            settings: {
              slidesToShow: 4,
              slidesToScroll: 1,
              infinite: true,
            },
          },
        
      {
        breakpoint: 1024,
        settings: {
          slidesToShow: 3,
          slidesToScroll: 1,
          infinite: true,
        },
      },
      {
        breakpoint: 743,
        settings: {
          slidesToShow: 2,
          slidesToScroll: 1,
        },
      },
      {
        breakpoint: 580,
        settings: {
          slidesToShow: 1,
          slidesToScroll: 1,
        },
      },
    ],
  };

 
  return (
    <>

    
      <Slider {...settings}>
        <div className={styles.sizes}>
          <div className={styles.mycard}>
            <div className="content">
              <h5 className={styles.name}>Fracht Group</h5>
              <p className={styles.position}>Auditor</p>
            </div>

            <div className={styles.stars}>
              <span>
                {" "}
                <span
                  className="fa fa-star"
                  style={{ color: "#FDD835" }}
                ></span>
                <span
                  className="fa fa-star"
                  style={{ color: "#FDD835" }}
                ></span>
                <span
                  className="fa fa-star"
                  style={{ color: "#FDD835" }}
                ></span>
                <span
                  className="fa fa-star"
                  style={{ color: "#FDD835" }}
                ></span>
                <span className="fa fa-star"  style={{ color: "#C5C5C5" }}></span>
              </span>
            </div>

            <div className="text">
              <p className={styles.para}>
                Their expertise in project accounting allowed us to optimize our
                project costs and improve efficiency
              </p>
            </div>
          </div>
        </div>

        <div className={styles.sizes}>
        <div className={styles.mycard}>
          <div className="content">
            <h5 className={styles.name}>Bioelys</h5>
            <p className={styles.position}>Manager</p>
          </div>

          <div className={styles.stars}>
            <span>
              {" "}
              <span className="fa fa-star" style={{ color: "#FDD835" }}></span>
              <span className="fa fa-star" style={{ color: "#FDD835" }}></span>
              <span className="fa fa-star" style={{ color: "#FDD835" }}></span>
              <span className="fa fa-star" style={{ color: "#FDD835" }}></span>
              <span className="fa fa-star" style={{ color: "#C5C5C5" }}></span>
            </span>
          </div>

          <div className="text">
            <p className={styles.para}>
              The financial reports generated by Maxims Auditors and consultants
              provided valuable insights into our business and helped us make
              informed decisions.
            </p>
          </div>
        </div>
        </div>


        <div className={styles.sizes}>
        <div className={styles.mycard}>
          <div className="content">
            <h5 className={styles.name}>ALJAR Trading</h5>
            <p className={styles.position}>Economist</p>
          </div>

          <div className={styles.stars}>
            <span>
              {" "}
              <span className="fa fa-star" style={{ color: "#FDD835" }}></span>
              <span className="fa fa-star" style={{ color: "#FDD835" }}></span>
              <span className="fa fa-star" style={{ color: "#FDD835" }}></span>
              <span className="fa fa-star" style={{ color: "#FDD835" }}></span>
              <span className="fa fa-star"  style={{ color: "#C5C5C5" }}></span>
            </span>
          </div>

          <div className="text">
            <p className={styles.para}>
              Their ability to manage large amounts of data ensured that all of
              our project records were complete and accurate.
            </p>
          </div>
        </div>
        </div>



        <div className={styles.sizes}>
        <div className={styles.mycard}>
          <div className="content">
            <h5 className={styles.name}>INTRADE commodites</h5>
            <p className={styles.position}>Director</p>
          </div>

          <div className={styles.stars}>
            <span>
              {" "}
              <span className="fa fa-star" style={{ color: "#FDD835" }}></span>
              <span className="fa fa-star" style={{ color: "#FDD835" }}></span>
              <span className="fa fa-star" style={{ color: "#FDD835" }}></span>
              <span className="fa fa-star" style={{ color: "#FDD835" }}></span>
              <span className="fa fa-star"  style={{ color: "#C5C5C5" }}></span>
            </span>
          </div>

          <div className="text">
            <p className={styles.para}>
            Their comprehensive stock analysis allowed us to identify areas for improvement in our inter-company management.
            </p>
          </div>
        </div>
        </div>

        <div className={styles.sizes}>
            <div className={styles.mycard}>
          <div className="content">
            <h5 className={styles.name}>Al Amaya</h5>
            <p className={styles.position}>Business Owner</p>
          </div>

          <div className={styles.stars}>
            <span>
              {" "}
              <span className="fa fa-star" style={{ color: "#FDD835" }}></span>
              <span className="fa fa-star" style={{ color: "#FDD835" }}></span>
              <span className="fa fa-star" style={{ color: "#FDD835" }}></span>
              <span className="fa fa-star" style={{ color: "#FDD835" }}></span>
              <span className="fa fa-star"  style={{ color: "#C5C5C5" }}></span>
            </span>
          </div>

          <div className="text">
            <p className={styles.para}>
            The team at Maxims Auditors and consultants helped us streamline our inventory management process, resulting in significant cost savings and improved accuracy.
            </p>
          </div>
        </div>
        </div>
      </Slider>
    </>
  );
}

export default Testimonialcards;
