import React from "react";
import styles from "../styles/testimonialcards.module.css";
import Slider from "react-slick";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

function Testimonialcards() {
  const settings = {
    dots: false,
    infinite: true,
    speed: 500,
    slidesToShow: 4,
    slidesToScroll: 1,
    autoplay: true,
    responsive: [
      {
        breakpoint: 2560,
        settings: {
          slidesToShow: 4,
          slidesToScroll: 1,
          infinite: true,
        },
      },

      {
        breakpoint: 1024,
        settings: {
          slidesToShow: 3,
          slidesToScroll: 1,
          infinite: true,
        },
      },
      {
        breakpoint: 743,
        settings: {
          slidesToShow: 2,
          slidesToScroll: 1,
        },
      },
      {
        breakpoint: 580,
        settings: {
          slidesToShow: 1,
          slidesToScroll: 1,
        },
      },
    ],
  };

  return (
    <>
   
      <h3 className={styles.heading}>Testimonial</h3>
      <p className={styles.heading2}>WHAT CLIENTS SAY</p>
      <div className={styles.linepar}>
        <hr className={styles.line}></hr>
      </div>
      
      <div className={styles.container}>
      <div className={styles.flexcontainer}>
        <div className={styles.card}>
          <h3 className={styles.name}>Fracht Group</h3>
          <div className={styles.stars}>
            <span className="fa fa-star" style={{ color: "#FDD835" }}></span>
            <span className="fa fa-star" style={{ color: "#FDD835" }}></span>
            <span className="fa fa-star" style={{ color: "#FDD835" }}></span>
            <span className="fa fa-star" style={{ color: "#FDD835" }}></span>
            <span className="fa fa-star" style={{ color: "#FDD835" }}></span>
          </div>
          <p className={styles.para}>
          Their expertise in project accounting allowed us to optimize our project costs and improve efficiency
          </p>
        </div>
        <div className={styles.card}>
          <h3 className={styles.name}>Bioelys</h3>

          <div className={styles.stars}>
            <span className="fa fa-star" style={{ color: "#FDD835" }}>
              <span className="fa fa-star" style={{ color: "#FDD835" }}></span>
              <span className="fa fa-star" style={{ color: "#FDD835" }}></span>
              <span className="fa fa-star" style={{ color: "#FDD835" }}></span>
              <span className="fa fa-star" style={{ color: "#FDD835" }}></span>
            </span>
          </div>

          <p className={styles.para}>
          The financial reports generated by Maxims Auditors and consultants provided valuable insights into our business and helped us make informed decisions.
          </p>
        </div>
        <div className={styles.card}>
          <h3 className={styles.name}>ALJAR Trading</h3>
          <div className={styles.stars}>
            <span className="fa fa-star" style={{ color: "#FDD835" }}>
              {" "}
            </span>
            <span className="fa fa-star" style={{ color: "#FDD835" }}></span>
            <span className="fa fa-star" style={{ color: "#FDD835" }}></span>
            <span className="fa fa-star" style={{ color: "#FDD835" }}></span>
            <span className="fa fa-star" style={{ color: "#FDD835" }}></span>
          </div>

          <p className={styles.para}>
          Their ability to manage large amounts of data ensured that all of our project records were complete and accurate.
          </p>
        </div>
        <div className={styles.card}>
          <h3 className={styles.name}>INTRADE commodites</h3>

          <div className={styles.stars}>
            <span className="fa fa-star" style={{ color: "#FDD835" }}>
              {" "}
            </span>
            <span className="fa fa-star" style={{ color: "#FDD835" }}></span>
            <span className="fa fa-star" style={{ color: "#FDD835" }}></span>
            <span className="fa fa-star" style={{ color: "#FDD835" }}></span>
            <span className="fa fa-star" style={{ color: "#FDD835" }}></span>
          </div>

          <p className={styles.para}>
          Their comprehensive stock analysis allowed us to identify areas for improvement in our inter-company management.
          </p>
        </div>
      </div>
      </div>
    </>
  );
}

export default Testimonialcards;
