import React from 'react'
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Slider from "react-slick";
import styles from "../styles/workoutcard.module.css";
import { HighlightTwoTone } from '@ant-design/icons';
function Workoutcard() {
    var settings = {
        dots: true,
        infinite: true,
        speed: 1000,
        slidesToShow: 3,
        slidesToScroll: 1,
        autoplay: true,
        arrows: false,
      
      };
  return (
    <div style={{}} >
        <div className="section-box" style={{marginTop:"80px"}}>
        <div className="banner-hero banner-homepage6">
          {/* <div className="container"> */}
            <div className="row">
        
                <div className={styles.box}>
         <div className={styles.slideContainer}>
     
            <div className={styles.sliderconten}>
            <Slider {...settings}>
                <div className={styles.cardwrapper}>
       
                    <div className={styles.card}>
                        <div className={ styles.imagecontent}>
                            <span className={styles.overlay}></span>
                            <div className={ styles.cardimage}>
                                <img src="assets\imgs\pexels-andrea-piacquadio-874158.jpg" alt='mmmm' className={styles.cardimg}></img>

                            </div>

                        </div>
                        <div className={styles.cardcontent}>
                            <h2 className={styles.name}>David Dell</h2>
                            <p className={styles.description}>The financial reports generated by Shadobooks provided valuable insights into our business and helped us make informed decisions.</p>
                            <button className={styles.button}>view more</button>
                        </div>

                    </div>
            
                </div>
                <div className={styles.cardwrapper}>
       
                    <div className={styles.card}>
                        <div className={ styles.imagecontent}>
                            <span className={styles.overlay}></span>
                            <div className={ styles.cardimage}>
                                <img src="assets\imgs\pexels-elle-hughes-1680175.jpg" alt='mmmm' className={styles.cardimg}></img>

                            </div>

                        </div>
                        <div className={styles.cardcontent}>
                            <h2 className={styles.name}>David Dell</h2>
                            <p className={styles.description}>The financial reports generated by Shadobooks provided valuable insights into our business and helped us make informed decisions.</p>
                            <button className={styles.button}>view more</button>
                        </div>

                    </div>
            
                </div>
                <div className={styles.cardwrapper}>
       
                    <div className={styles.card}>
                        <div className={ styles.imagecontent}>
                            <span className={styles.overlay}></span>
                            <div className={ styles.cardimage}>
                                <img src="assets\imgs\pexels-pixabay-220453.jpg" alt='mmmm' className={styles.cardimg}></img>

                            </div>

                        </div>
                        <div className={styles.cardcontent}>
                            <h2 className={styles.name}>David Dell</h2>
                            <p className={styles.description}>The financial reports generated by Shadobooks provided valuable insights into our business and helped us make informed decisions.</p>
                            <button className={styles.button}>view more</button>
                        </div>

                    </div>
            
                </div>
                <div className={styles.cardwrapper}>
       
                    <div className={styles.card}>
                        <div className={ styles.imagecontent}>
                            <span className={styles.overlay}></span>
                            <div className={ styles.cardimage}>
                                <img src="\assets\imgs\pexels-doug-bolton-1445527.jpg" alt='mmmm' className={styles.cardimg}></img>

                            </div>

                        </div>
                        <div className={styles.cardcontent}>
                            <h2 className={styles.name}>David Dell</h2>
                            <p className={styles.description}>The financial reports generated by Shadobooks provided valuable insights into our business and helped us make informed decisions.</p>
                            <button className={styles.button}>view more</button>
                        </div>

                    </div>
            
                </div>
                <div className={styles.cardwrapper}>
       
                    <div className={styles.card}>
                        <div className={ styles.imagecontent}>
                            <span className={styles.overlay}></span>
                            <div className={ styles.cardimage}>
                                <img src="assets\imgs\pexels-andrea-piacquadio-839586.jpg" alt='mmmm' className={styles.cardimg}></img>

                            </div>

                        </div>
                        <div className={styles.cardcontent}>
                            <h2 className={styles.name}>David Dell</h2>
                            <p className={styles.description}>The financial reports generated by Shadobooks provided valuable insights into our business and helped us make informed decisions.</p>
                            <button className={styles.button}>view more</button>
                        </div>

                    </div>
            
                </div>
                </Slider>
               
            </div>
         </div>
         </div>
         
 
         </div>
         {/* </div> */}
         </div>
         </div> 

    </div>
  )
}

export default Workoutcard; 